# cargo-deny configuration
# Run with: cargo deny check

[advisories]
# Deny crates with security vulnerabilities
vulnerability = "deny"
# Warn about unmaintained crates
unmaintained = "warn"
# Warn about unsound crates
unsound = "warn"
# Warn about yanked crates
yanked = "warn"
# Ignore specific advisories (none currently)
ignore = []

[licenses]
# Allow only specific licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Zlib",
]
# Deny copyleft licenses
deny = [
    "GPL-2.0",
    "GPL-3.0",
    "AGPL-3.0",
]
# Confidence threshold for license detection
confidence-threshold = 0.8

[bans]
# Deny multiple versions of the same crate
multiple-versions = "warn"
# Allow specific duplicate crates
skip = []
# Deny wildcard dependencies
wildcards = "deny"
# Warn about git dependencies (prefer crates.io)
allow-wildcard-paths = false

[sources]
# Deny git sources (prefer crates.io releases)
unknown-git = "warn"
# Allow crates.io as source
allow-org = { github = ["FractionEstate"] }
