# Rust formatting configuration for cardano-base-rust
# Run with: cargo fmt

edition = "2021"

# Line length
max_width = 100

# Formatting style
use_field_init_shorthand = true
use_try_shorthand = true

# Function definitions
fn_params_layout = "Tall"

# Match expressions
match_block_trailing_comma = true

# Chains
chain_width = 60

# Misc
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
