# Cardano Base Rust - Documentation Site

title: Cardano Base Rust
description: Pure Rust implementation of Cardano base libraries
baseurl: ""
url: "https://fractionestate.github.io"

# Build settings
markdown: kramdown
theme: minima

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata

# Collections
collections:
  audit:
    output: true
    permalink: /audit/:name/
  guides:
    output: true
    permalink: /guides/:name/
  api:
    output: true
    permalink: /api/:name/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_audit"
    values:
      layout: "page"
      category: "Audit Reports"
  - scope:
      path: "_guides"
    values:
      layout: "page"
      category: "Guides"
  - scope:
      path: "_api"
    values:
      layout: "page"
      category: "API Documentation"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO
author: FractionEstate
twitter:
  username: fractionestate
  card: summary

# Navigation
nav_links:
  - title: Home
    url: /
  - title: Getting Started
    url: /guides/getting-started/
  - title: API Documentation
    url: /api/
  - title: Audit Reports
    url: /audit/
  - title: Contributing
    url: /contributing/
  - title: GitHub
    url: https://github.com/FractionEstate/cardano-base-rust
    external: true
